# Example Firewall Configuration

# ---------- IP Rules ----------

allow_ip=192.168.1.5
block_ip=192.168.1.50

# ---------- TCP Rules ----------

allow_tcp=22
allow_tcp=443

block_tcp=80
block_tcp=23

# ---------- UDP Rules ----------

allow_udp=53

block_udp=69
block_udp=161
