# =========================================
# eBPF XDP Firewall Configuration
# =========================================

# Allowed IPs
allow_ip=192.168.1.10
allow_ip=192.168.1.20

# Blocked IPs
block_ip=192.168.1.100
block_ip=10.0.0.5

# Allowed TCP Ports
allow_tcp=22
allow_tcp=443

# Blocked TCP Ports
block_tcp=23
block_tcp=80

# Allowed UDP Ports
allow_udp=53

# Blocked UDP Ports
block_udp=69
block_udp=123
